name: ShellCheck
on:
  push:
    paths:
      - 'srafq'
      - 'scripts/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'srafq'
      - 'scripts/**'
      - '.github/workflows/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          severity: warning
