name: ShellCheck
on:
  push:
    paths:
      - 'srafq'
      - 'scripts/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'srafq'
      - 'scripts/**'
      - '.github/workflows/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38
        with:
          severity: warning
